#ifndef MINECRAFT_SHADERTYPE_H
#define MINECRAFT_SHADERTYPE_H

#include <GL/glew.h>

enum ShaderType
{
    VERTEX = GL_VERTEX_SHADER,
    TESSELLATION_CONTROL = GL_TESS_CONTROL_SHADER,
    TESSELLATION_EVALUATION = GL_TESS_EVALUATION_SHADER,
    GEOMETRY = GL_GEOMETRY_SHADER,
    FRAGMENT = GL_FRAGMENT_SHADER,
    COMPUTE = GL_COMPUTE_SHADER
};

#endif //MINECRAFT_SHADERTYPE_H
